%root Program
%import './token.ebnf'

Program = {TopLevelStatement} Main {TopLevelStatement};

TopLevelStatement = Declaration | Definition;

    Declaration = (CONST | LET | PURE) IDENTIFIER ":" TypeSignature ";";
    Definition = Declaration "=" Expression ";";

        Expression = Lamda | Term | BooleanExpression;

        %import './function.ebnf'

        %import './term.ebnf'

        %import './booleanExpression.ebnf'

Main = MAIN [TypeSignature] "=" Lamda;

    %import './type.ebnf'
